spring.mvc.view.prefix=/WEB-INF/JSP/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:3432/adminpaneldb
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db.changelog/master.xml
spring.liquibase.enabled=true
liquibase.secure-parsing=false

repository.type=database